### ISSUE TITLE
Ability to start empty public lobby 

### ISSUE THREAD

**Issue by GitCat3** [Mr-X-GTA/YimMenu#48]
### Problem

I am tired of people hacking with host

### Solution

Add the ability to create a new empty public lobby

### Reason

I would love the ability to start an empty public lobby so I don't have to deal with hackers with host anymore

**Comment by tupoy-ya** [comment]
It already exists in the network tab:
https://github.com/Mr-X-GTA/YimMenu/blob/6edc483502c2cff6fd278072a5dc32ca57d29e40/src/views/network/view_network.cpp#L118-L126

Select "New Public Session" and it will create a new session.

YimMenu also has a `joinsession` command, I don't know how to use it, but I guess you need to pass "NEWPUB" as the argument for it to create a new session.

##### Did not test this since Battleye was added.
